backend:
  name: git-gateway
  branch: main

media_folder: "images/téléchargements"
public_folder: "/images/téléchargements"

collections:
  - name: "offres"
    label: "Nos Offres et Activités"
    folder: "Contenu/offres"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre de l'activité", name: "titre", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Image d'illustration", name: "image", widget: "image" }
      - { label: "Description de l'offre", name: "body", widget: "markdown" }
