backend:
  name: github
  repo: agisaacng1-alt/isanh-global
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "offres"
    label: "Nos Offres et Activités"
    folder: "content/offres"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre de l'activité", name: "title", widget: "string" }
      - { label: "Date de publication", name: "date", widget: "datetime" }
      - { label: "Image d'illustration", name: "image", widget: "image" }
      - { label: "Description de l'offre", name: "body", widget: "markdown" }
