backend:
  name: git-gateway
  branch: main

media_folder: "images/téléchargements"
public_folder: "/images/téléchargements"

collections:
  - name: "publications"
    label: "Publications"
    folder: "content/publications" # Dossier où sont enregistrés vos fichiers
    create: true
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Catégorie", name: "category", widget: "select", options: ["Activités Réalisées", "Offres & Recrutements", "Projets à Financer"]}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Contenu", name: "body", widget: "markdown"}
